version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_LOG}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
      
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: ["python", "-u", "bot"]
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ./logs:/app/logs

  site:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: ["python", "-u", "webadmin"]
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ./logs:/app/logs
      
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - site
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres-data: